### ISSUE TITLE
Switching from lightwave2

### ISSUE THREAD

**Issue by SGXander** [LightwaveSmartHome/homeassistant-lightwave-smart#16]
Is there a guide on migrating from https://github.com/bigbadblunt/homeassistant-lightwave2 to this fork?
It says the entities are created differently, Is there a mapping to follow?
Given the different name, can it be installed side-by-side for easier migration?

Thanks in advance

**Comment by paulhugill** [comment]
Was just looking for this too but can't see anything.

Sounds like there are a few places that need to change:
- Entity names
- Button Click events (even the legacy version seems to have changed name)
- Set brightness action has changed name

Would be helpful to get over to this version as I am seeing the issue of it loosing connection on HA restart, which I think is fixed in this.

**Comment by ikb42** [comment]
@SGXander to my knowledge there isn't a guide to migrating
I *think* it could be installed side-by-side, have not tried

@paulhugill the connection should be more stable in this version
