### ISSUE TITLE
HASS 2024.1.x  - Energy Monitor - Error creating sensors

### ISSUE THREAD

**Issue by xela1** [LightwaveSmartHome/homeassistant-lightwave-smart#5]
I've noticed an error when the integration starts, complaining about setting entity_category to none when an entity 'is_energy'.

I believe this call is only for the Energy Monitor 

```
2024-01-20 14:54:11.415 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up lightwave_smart platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lightwave_smart/sensor.py", line 108, in async_setup_entry
    sensors.append(LWRF2Sensor(featureset.name, featureset_id, link, description, hass))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwave_smart/sensor.py", line 155, in __init__
    self.entity_description.entity_category = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'entity_category'
```

The lines with the error are

```
        if self._lwlink.featuresets[self._featureset_id].is_energy() and not self.entity_description.key == 'rssi':
            self.entity_description.entity_category = None
```

I can't work out what exactly the problem is, but from what I can see on https://developers.home-assistant.io/docs/core/entity/#registry-properties the default is None anyway so the code seems unnecessary?

**Comment by ikb42** [comment]
Thanks for spotting this and the pull request!  I see, a can of worms :-)  
It turns out this relates to "primary" entities, as hinted to with the description of entity_category that you point to.
The code here is trying to expose sensors that are primarily energy focused as "primary" entities in HA by removing the otherwise DIAGNOSTIC entity_category that is being applied generally - which is now failing.

I've added a new check for primary "energy" devices, see this commit:
https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/commit/8793b65f4473ea6beb7ed9d9f9347d6835c3970c

Also a new release: 
https://github.com/LightwaveSmartHome/homeassistant-lightwave-smart/releases/tag/v3.5.29

Would be good to know if this version fixes your issue.

It does raise a bigger question for the integration in general, that is what should be exposed at the "primary" level and what shouldn't.

**Comment by ikb42** [comment]
To test , just that it all works otherwise as you would expect. Any energy monitors you have should show as entities on the default overview.

Re 'Last Event Received', very likely I did 'break' that, I'll look to fix it. Out of interest what kind of use cases is this put to?

**Comment by xela1** [comment]
The reason last event received exists is due to the issue the Websocket had quite some time back where after a seemingly random amount of time, the lightwave server would stop forwarding the events to the connected clients. People created automations based on the last event received and if it was over 'x' they would reconnect the websocket. 

As the websocket is now fixed, it's original purpose isn't really needed, but I still like to use it to check that everything is ok (for example at 6am this morning my connection to the websocket died)

I'll roll back to an early version of the code on my test instance tomorrow and see what I can work out

**Comment by ikb42** [comment]
Ah I see, yes, the websocket should not stop receiving events anymore, that was addressed on the Lightwave side.
Your issue though where the connection to the websocket died, that's no good. I'm just guessing but maybe the websocket does not reconnect if it is dropped for whatever reason.

Logging / debugging around that could be useful.

BTW, I'm just preparing a fix for the 'Last Event Received', will push that in the next 15 mins or so.
It does concern me a bit, not sure if it should, because this will be a very "hot" event even if you don't have an Energy monitor, but more so with an Energy monitor.  The HA database is going to be rather busy storing all these events.

**Comment by xela1** [comment]
Maybe it could be a disabled entity and people can enable it if wanted?
Just a thought

Yeah, sorry, I thought I'd saved the logs before I restarted my container,
but I can't find them now, it was trying to reconnect but was failing to
reauthenticate, if it happens again I'll definitely send the logs

**Comment by ikb42** [comment]
That's a much better idea, disabled by default.  I've just looked at that, there is an option for this here:
https://developers.home-assistant.io/docs/entity_registry_disabled_by/
But it's not working for me at the moment, going to hold back on fixing this and see if I can get disabling to work first.

**Comment by ikb42** [comment]
Ok that's done now, you should have the Last Event Received entity working again in latest release.
Note it is disabled by default as per the above, enabling/disabling does require a subsequent HA restart.
I'll close this one for now, please feel free to re-open or comment further though.
